# Generated by Django 2.2.28 on 2022-09-02 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('cardio', models.BooleanField(default=False)),
                ('cardio_length', models.PositiveIntegerField()),
                ('cardio_frequency', models.PositiveIntegerField()),
                ('heart_rate', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=250)),
                ('protein', models.FloatField()),
                ('carb', models.FloatField()),
                ('carb_casual', models.FloatField()),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('exercise_id', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('video', models.FileField(null=True, upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise_type_images')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_exercises', to='program.Day')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('name', models.CharField(max_length=500, null=True)),
                ('cardio', models.BooleanField(blank=True, default=False, null=True)),
                ('cardio_length', models.PositiveIntegerField(blank=True, null=True)),
                ('cardio_frequency', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('carb', models.FloatField(blank=True, null=True)),
                ('carb_casual', models.FloatField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='program.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('timer', models.FloatField(default=90.0)),
                ('done', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='program.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='program.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_no', models.PositiveIntegerField(default=1)),
                ('reps', models.CharField(default='1', max_length=150)),
                ('weight', models.CharField(default='1', max_length=250)),
                ('timer', models.FloatField(default=90.0)),
                ('set_type', models.CharField(choices=[('ss', 'Superset'), ('gs', 'Giantset'), ('ds', 'Dropset'), ('td', 'Triple Dropset'), ('ct', 'Circuit Training'), ('r', 'Regular'), ('cr', 'Cardio')], default='r', max_length=10)),
                ('done', models.BooleanField(default=False)),
                ('exercises', models.ManyToManyField(blank=True, to='program.Exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='program.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='program.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_no', models.PositiveIntegerField(default=1)),
                ('reps', models.CharField(default='1', max_length=150)),
                ('weight', models.CharField(default='1', max_length=250)),
                ('timer', models.FloatField(default=90.0)),
                ('set_type', models.CharField(choices=[('ss', 'Superset'), ('gs', 'Giantset'), ('ds', 'Dropset'), ('td', 'Triple Dropset'), ('ct', 'Circuit Training'), ('r', 'Regular'), ('cr', 'Cardio')], default='r', max_length=10)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_exercie_sets', to='program.ProgramExercise')),
                ('exercises', models.ManyToManyField(blank=True, to='program.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramExerciseReplacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='program.ProgramExercise')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exercise_images')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='program.Exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='program.ExerciseType'),
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='program.Week'),
        ),
    ]
