# Generated by Django 2.2.28 on 2022-09-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
