# Generated by Django 2.2.28 on 2022-09-15 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_exercise_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='done',
        ),
    ]
