# Generated by Django 2.2.28 on 2024-01-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20220922_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='exercise_video/thumbnail'),
        ),
    ]
