# Generated by Django 2.2.28 on 2024-01-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_exercise_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
