# Generated by Django 2.2.28 on 2024-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_session_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
