# Generated by Django 2.2.28 on 2024-02-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20240131_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['done']},
        ),
    ]
