# Generated by Django 2.2.28 on 2024-02-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20240223_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='sets_exercises', to='program.Exercise'),
        ),
    ]
