# Generated by Django 2.2.28 on 2024-02-29 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0012_auto_20240228_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('done', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_workouts', to='program.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_workouts_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_no', models.PositiveIntegerField(default=1)),
                ('reps', models.CharField(default='1', max_length=150)),
                ('weight', models.CharField(default='1', max_length=250)),
                ('timer', models.FloatField(default=90.0)),
                ('set_type', models.CharField(choices=[('ss', 'Superset'), ('gs', 'Giantset'), ('ds', 'Dropset'), ('td', 'Triple Dropset'), ('ct', 'Circuit Training'), ('r', 'Regular'), ('cr', 'Cardio')], default='r', max_length=10)),
                ('done', models.BooleanField(default=False)),
                ('custom_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_set_exercises', to='program.CustomExercise')),
                ('exercises', models.ManyToManyField(blank=True, related_name='custom_sets_exercises', to='program.Exercise')),
            ],
        ),
        migrations.AddField(
            model_name='customexercise',
            name='custom_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_workouts_exercises', to='program.CustomWorkout'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_multiple_exercises', to='program.Exercise'),
        ),
    ]
