# Generated by Django 2.2.28 on 2024-02-29 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_auto_20240229_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customexercise',
            name='exercise',
        ),
        migrations.AddField(
            model_name='customexercise',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='custom_workout_exercises', to='program.Exercise'),
        ),
        migrations.AddField(
            model_name='customexercise',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customexercise',
            name='custom_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises_workouts', to='program.CustomWorkout'),
        ),
    ]
