# Generated by Django 2.2.28 on 2024-03-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_auto_20240229_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='customset',
            name='rest',
            field=models.CharField(default='1', max_length=150),
        ),
    ]
