# Generated by Django 2.2.28 on 2024-03-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_customset_rest'),
    ]

    operations = [
        migrations.AddField(
            model_name='programexercise',
            name='exercises',
            field=models.ManyToManyField(related_name='program_exercises', to='program.Exercise'),
        ),
        migrations.AddField(
            model_name='programexercise',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Exercise'),
        ),
    ]
