# Generated by Django 2.2.28 on 2024-03-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0016_auto_20240307_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programexercise',
            name='exercises',
            field=models.ManyToManyField(blank=True, null=True, related_name='program_exercises', to='program.Exercise'),
        ),
    ]
