# Generated by Django 2.2.28 on 2024-03-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0018_auto_20240308_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='day_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='week_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
