# Generated by Django 2.2.28 on 2024-05-13 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0019_auto_20240313_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customworkout',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
