# Generated by Django 2.2.28 on 2024-05-13 13:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0020_auto_20240513_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='customexercise',
            name='exercises_order',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
