# Generated by Django 2.2.28 on 2024-06-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0021_customexercise_exercises_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programexercise',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
