
export default {
  HomeOn: require('src/assets/images/home_On.png'),
  HomeOff: require('src/assets/images/home_off.png'),
  HomeImage: require('src/assets/images/home_page.png'),
  AccountOn: require('src/assets/images/account_on.png'),
  AccountOff: require('src/assets/images/account_off.png'),
  CollabOn: require('src/assets/images/collab_on.png'),
  CollabOff: require('src/assets/images/collab_off.png'),
  Camera: require('src/assets/images/camera.png'),
  ExploreOn: require('src/assets/images/explore_on.png'),
  ExploreOff: require('src/assets/images/explore_off.png'),
  Logo: require('src/assets/images/logo.png'),
  Incognito: require('src/assets/images/incognito.png'),
  Bell: require('src/assets/images/bell.png'),
  Check_in: require('src/assets/images/check_in.png'),
  ForYou: require('src/assets/images/for_you.png'),
  DotIcon: require('src/assets/images/dotIcon.png'),
  Follow: require('src/assets/images/follow.png'),
  FollowOff: require('src/assets/images/followOff.png'),
  ForYouOff: require('src/assets/images/forYouOff.png'),
  IncognitoOff: require('src/assets/images/incognitoOff.png'),
  googleIcon: require('src/assets/images/googleIcon.png'),
  facebookButton: require('src/assets/images/faceBookIcon.png'),
  orumIcon: require('src/assets/images/orumIcon.png'),
  backIcon: require('src/assets/images/Backicon.png'),
  home: require('src/assets/images/home.png'),
  profile: require('src/assets/images/profile.png'),
  feed: require('src/assets/images/feed.png'),
  nutrition: require('src/assets/images/nutrition.png'),
  exercise: require('src/assets/images/exercise.png'),
  etc: require('src/assets/images/etc.png'),
  addIcon: require('src/assets/images/add.png'),
  searchIcon: require('src/assets/images/search.png'),
  heartIcon: require('src/assets/images/heart.png'),
  shareIcon: require('src/assets/images/share.png'),
  messageIcon: require('src/assets/images/message.png'),
  foodImage: require('src/assets/images/food.jpeg'),
  backArrow: require('src/assets/images/back.png'),
  faceBookIcon: require('src/assets/images/FacebookIcon.png'),
  smallGoogleIcon: require('src/assets/images/GoogleIcon.png'),
  closeIcon: require('src/assets/images/closeIcon.png'),
  colorAddIcon: require('src/assets/images/addIcon.png'),
  circleClose: require('src/assets/images/circleClose.png'),
  fillheart: require('src/assets/images/filledHeart.png'),

}
