# Generated by Django 2.2.28 on 2024-01-02 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_reportcommentreply'),
        ('notification', '0003_auto_20231213_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_report', to='home.Post'),
        ),
    ]
