# Generated by Django 2.2.28 on 2024-01-24 07:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
