# Generated by Django 2.2.28 on 2022-09-05 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_answer_blockuser_caloriesrequired_category_chat_comment_consumecalories_favoriterecipe_food_fooditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImageVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='post_image/image')),
                ('video', models.FileField(blank=True, null=True, upload_to='post_video/video')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_image_video', to='home.Post')),
            ],
        ),
    ]
