# Generated by Django 2.2.28 on 2022-09-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_postimagevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_thumbnail',
        ),
        migrations.AddField(
            model_name='postimagevideo',
            name='video_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='post_video/thumbnail'),
        ),
    ]
