# Generated by Django 2.2.28 on 2022-09-07 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_postcommentlike_postcommentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcommentlike',
            name='comment_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', to='home.PostCommentReply'),
        ),
        migrations.AlterField(
            model_name='postcommentlike',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_like', to='home.Comment'),
        ),
    ]
