# Generated by Django 2.2.28 on 2022-09-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220907_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentlike',
            name='comment_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_like_reply', to='home.PostCommentReply'),
        ),
    ]
