# Generated by Django 2.2.28 on 2022-09-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220912_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
