# Generated by Django 2.2.28 on 2022-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_reportauser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='video_thumbnail',
        ),
        migrations.AddField(
            model_name='postvideo',
            name='video_thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='post_video/thumbnail'),
        ),
    ]
