# Generated by Django 2.2.28 on 2024-01-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20240122_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altmeasure',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='home.FoodItem'),
        ),
        migrations.AlterField(
            model_name='altmeasure',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_measures', to='home.Meal'),
        ),
    ]
