# Generated by Django 2.2.28 on 2024-01-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20240122_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
