# Generated by Django 2.2.28 on 2024-01-27 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0021_auto_20240126_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altmeasure',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='date_time',
        ),
        migrations.AddField(
            model_name='meal',
            name='no_of_meals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('meal_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_meals', to='home.Meal')),
            ],
        ),
        migrations.CreateModel(
            name='MealHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date_time', models.DateTimeField(blank=True, null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_history', to='home.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_history_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='altmeasure',
            name='meal_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_history_measures', to='home.MealHistory'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='meal_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items_history', to='home.MealHistory'),
        ),
    ]
