# Generated by Django 2.2.28 on 2024-01-27 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20240127_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='meal_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_items_times', to='home.MealTime'),
        ),
    ]
