# Generated by Django 2.2.28 on 2024-01-28 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_fooditem_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
