# Generated by Django 2.2.28 on 2024-03-18 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0024_auto_20240128_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_at', models.DateTimeField()),
                ('subscription_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cancel_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
