# Generated by Django 2.2.28 on 2024-03-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_cancelsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelsubscription',
            name='cancel_at',
        ),
        migrations.AddField(
            model_name='cancelsubscription',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancelsubscription',
            name='is_subscription_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cancelsubscription',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancelsubscription',
            name='subscription_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
