# Generated by Django 2.2.28 on 2024-03-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20240320_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelsubscription',
            name='is_subscription_days_remaining',
            field=models.BooleanField(default=False),
        ),
    ]
