# Generated by Django 2.2.28 on 2024-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_duplicatecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloriesrequired',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='caloriesrequired',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='caloriesrequired',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='caloriesrequired',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
    ]
