# Generated by Django 2.2.28 on 2022-09-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220901_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ob',
            new_name='dob',
        ),
    ]
