# Generated by Django 2.2.28 on 2022-09-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('users', '0003_auto_20220901_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.PositiveIntegerField()),
                ('age_max', models.PositiveIntegerField()),
                ('exercise_level', models.PositiveIntegerField(blank=True, null=True)),
                ('activity_level', models.PositiveIntegerField(blank=True, null=True)),
                ('understanding_level', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_meal', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_training_days', models.PositiveIntegerField(blank=True, null=True)),
                ('fitness_goal', models.PositiveIntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program')),
            ],
        ),
    ]
