# Generated by Django 2.2.28 on 2024-02-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_uservideo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
