# Generated by Django 2.2.28 on 2024-02-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20240202_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium_user',
            field=models.BooleanField(default=False),
        ),
    ]
